### PR TITLE
Check for property value objects that would have originally been Soft…

### PR DESCRIPTION
**Pull request by colingourlay**
…SetHooks, and ensure their nested value is used.

This addresses Issue #2

### CODE REVIEW

**Comment by nolanlawson** [comment]
Looks great to me, but would it be possible to add a test to check for this?

**Comment by nolanlawson** [comment]
BTW I recently made the tests [a little easier to run](https://github.com/nolanlawson/vdom-serialized-patch#testing-this-library); it should be as easy as adding a few new `<div>` to the big list of test divs in `test.js` (the test just compares each div to each other div, round-robin).

**Comment by nolanlawson** [comment]
btw there are now coverage tests that can make it a little easier to tell if your test is working: just do `npm run coverage` and then open up `coverage/lcov-report/index.html` in a browser.

**Comment by colingourlay** [comment]
Thanks for adding in this testing workflow.

After pulling in your latest changes, I was able to confirm that your existing tests contained two `input` elements (`text` & `number`) with defined value properties that are correctly handed by the mock SoftSetHook. This is confirmed by the coverage tests.

I've added another `input` to the tests just to make sure something I added is also handled correctly.

**Comment by nolanlawson** [comment]
Sweet, thanks a lot! LGTM. :)

**Comment by nolanlawson** [comment]
Released in 1.0.5

**Comment by colingourlay** [comment]
Cheers! :+1:

**Pull request merged**
